# Generated by Django 4.2.16 on 2024-09-28 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploads',
            name='excerpt',
            field=models.TextField(blank=True),
        ),
    ]
