# Generated by Django 4.2.16 on 2024-09-28 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_uploads_excerpt'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploads',
            name='updated_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
