# Generated by Django 4.2.16 on 2024-09-29 00:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_commenting'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commenting',
            options={'ordering': ['created_on']},
        ),
        migrations.AlterModelOptions(
            name='uploads',
            options={'ordering': ['-created_on']},
        ),
    ]
