# Generated by Django 4.2.19 on 2025-04-23 13:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("news", "0006_alter_uploads_author"),
    ]

    operations = [
        migrations.AlterField(
            model_name="uploads",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="news_uploads",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
